### PR TITLE
TransferPlaylistInteractor

### PR DESCRIPTION
**Pull request by gburnham03**
I have created a high-level desgin of the TransferPlaylistInteractor class. For implementation, I will need to access the playlist objects from both Spotify and Amazon Music. Going to work on implementing these methods within this class.

### CODE REVIEW

**Review by TeenI126 — COMMENTED** [review]
Rather follow the inverse dependency principle and make it so it can transfer from any two playlists from any music service, instead of having multiple cases of spotify to amazon and amazon to spotify. 

In terms of implementation, the methods to add and get playlists will be in the music service data object (e.g. SpotifyDataAccessObject). Just make any methods you need and whoever is in charge of the DataAccessObjects will get around to implementing it, or try creating the method yourself.

**Comment by TeenI126** [comment]
> Rather follow the inverse dependency principle and make it so it can transfer from any two playlists from any music service, instead of having multiple cases of spotify to amazon and amazon to spotify.
> 
> In terms of implementation, the methods to add and get playlists will be in the music service data object (e.g. SpotifyDataAccessObject). Just make any methods you need and whoever is in charge of the DataAccessObjects will get around to implementing it, or try creating the method yourself.

Wait looking through CA stuff from the week five thing we had to do make the methods you need via a dataAccessInterface, then make the dataAccessObjects for Spotify and Amazon implement them.

**Comment by TeenI126** [comment]
Also waiting on a second review before we approve, so they seem well 'reviewed'.

**Comment by lamkevin7** [comment]
I agree with Mateen on that you should follow the inversion dependency principle so that we can transfer playlists in any direction instead of having to consider individual cases (i.e amazon to spotify, spotify to amazon)

**Review by TeenI126 — APPROVED** [review]
Approving now

**Pull request closed without merging**
