### PR TITLE
Created Amazon Music Account Entity

### PR DESCRIPTION
**Pull request by daniel-makarov**
Created a Amazon Music Account Entity where users can get their accounts, and retrieve their playlists.

### CODE REVIEW

**Review by TeenI126 — COMMENTED** [review]
Cool. May have to move over some of the data access functionality to a AmazonServiceDataAccessObject type class, since I think that satisfies CA more. Also from my experience with Spotify and other APIs, usually you get a refresh token with the authToken, otherwise API access will expire an hour the access token is given.

Also javadocs, since example reviews we went over in TUT also mention those, and might be required for the marks  (maybeee).

I let others review before approval

**Comment by TeenI126** [comment]
Secrets.java must be unversioned!

**Comment by gburnham03** [comment]
I agree with Mateen, just to hit the CA marks on our presentation it might be beneficial to refactor the code so that the Amazon's account data access is moved to a AmazonServiceDataAccessObject, other than that good work! It seems to be tested well and will we go ahead with using this to further implement our project.

**Review by gburnham03 — APPROVED** [review]
Looks good! Preview Mateen and I's comments for some inspiration on next steps.

**Pull request merged**
